version: '3'
services:
  wic-mongo:
    build:
      context: ./wic-mongo
    image: wichan7/wic-mongo:0.0.3
    ports:
      - 27017:27017
  wic-redis:
    build:
      context: ./wic-redis
    image: wichan7/wic-redis:0.0.3
    ports:
      - 6379:6379
  wic-api:
    build:
      context: ./wic-api
    image: wichan7/wic-api:0.0.3
    ports:
      - 3311:3311
    environment:
      - PORT=3311
      - MONGO_URI=mongodb://wic-mongo:27017/wic
  wic-dashboard:
    build:
      context: ./wic-dashboard
    image: wichan7/wic-dashboard:0.0.3
    ports:
      - 3310:3310
    environment:
      - PORT=3310
      - MONGO_URI=mongodb://wic-mongo:27017/wic