apiVersion: v1
kind: Service
metadata:
  name: wic-api
  namespace: wic
spec:
  type: ClusterIP
  selector:
    app: wic-api
  ports:
    - name: api
      port: 3311
      targetPort: 3311
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wic-api-deployment
  namespace: wic
  labels:
    app: wic-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wic-api
  template:
    metadata:
      labels:
        app: wic-api
    spec:
      containers:
      - name: wic-api
        image: wichan7/wic-api:latest
        ports:
        - containerPort: 3311
        env:
        - name: PORT
          value: "3311"
        - name: MONGO_URI
          value: "mongodb://mongo-primary-0:27017/wic"